### ISSUE TITLE
browserid-verifier - docker build failed

### ISSUE THREAD

**Issue by misterhsp** [mozilla/browserid-verifier#113]
docker build failed on Debian Stretch.

see paste.
https://paste.debian.net/1040699/

**Comment by vladikoff** [comment]
Could be a node v10 update that broke, might have to rollback to a different point release of v10

**Comment by rfk** [comment]
Pulling context out of the pastebin, this appears to be a failure to build the bignum dependency:

```
> bignum@0.12.5 install /app/node_modules/bignum
> node-pre-gyp install --fallback-to-build

[91mnode-pre-gyp ERR! Tried to download(403): https://rvagg-node.s3-us-west-2.amazonaws.com/bignum/v0.12.5/bignum-v0.12.5-node-v64-linux-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for bignum@0.12.5 and node@10.9.0 (node-v64 ABI, musl) (falling back to source compile with node-gyp) 
[0m[91mnode-pre-gyp ERR! Tried to download(undefined): https://rvagg-node.s3-us-west-2.amazonaws.com/bignum/v0.12.5/bignum-v0.12.5-node-v64-linux-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for bignum@0.12.5 and node@10.9.0 (node-v64 ABI, musl) (falling back to source compile with node-gyp) 
[0mmake: Entering directory '/app/node_modules/bignum/build'
  ACTION Regenerating Makefile
  CXX(target) Release/obj.target/bignum/bignum.o
make: Entering directory '/app/node_modules/bignum/build'
  CXX(target) Release/obj.target/bignum/bignum.o
[91m../bignum.cc: In function 'int BN_jacobi_priv(const BIGNUM*, const BIGNUM*, int*, BN_CTX*)':
../bignum.cc:143:6: error: expected '(' before 'BN_is_zero'
   if BN_is_zero(a1) /* step 1 */
      ^~~~~~~~~~
```

It's pinned to v0.12.5 in `npm-shrinkwrapjson`, but there's a v0.13.0 that was released recently.  We could try updating to that.

**Comment by rfk** [comment]
Indeed the commit log says things like "update deps, switch to prebuild, make work for node 10" which seems promising.

**Comment by rfk** [comment]
This dependency comes from browserid-crypto, which hard-codes it at that specific version.  So we'll need updates to -crypto, -local-verify, and -verifier here 😢; started in  https://github.com/mozilla/browserid-crypto/pull/113

**Comment by rfk** [comment]
See also https://github.com/mozilla/browserid-verifier/pull/114
