### ISSUE TITLE
err type issue

### ISSUE THREAD

**Issue by jbuck** [mozilla/browserid-verifier#130]
Most of the time the `err` key is a string but sometimes it gets converted into an object, which causes BigQuery to be sad. Here's an example of a log message that triggers this error:

`{"insertId":"1vzqeyyfoqj745","jsonPayload":{"agent":"python-requests/2.7.0 CPython/2.7.13 Linux/3.2.40","api":2,"code":400,"err":{"code":400,"reason":"missing audience parameter"},"hostname":"ip-172-31-27-186.us-west-2.compute.internal","name":"bid.summary","op":"bid.summary","pid":16,"remoteAddressChain":["127.0.0.1"],"rp":"","v":1},"labels":{"application":"fxa","compute.googleapis.com/resource_name":"fxa-prod-default-fxa_verifier","env":"prod","stack":"default","type":"fxa_verifier"},"logName":"projects/moz-fx-fxa-prod-0712/logs/docker.fxa-verifier","receiveTimestamp":"2019-01-30T09:40:14.953986696Z","resource":{"labels":{"instance_id":"i-076ea1b1ea3af7769","project_id":"moz-fx-fxa-prod-0712","zone":"us-west-2b"},"type":"gce_instance"},"timestamp":"2019-01-30T09:40:14.953986696Z"}`

**Comment by rfk** [comment]
@jbuck what's the right thing here, should we coerce it to always be a string, or coerces strings into a fake object? Not sure which would be easier for BigQuery to handle.

**Comment by jbuck** [comment]
It can handle either, it's capable of querying arbitrary JSON objects so long as the types stay the same for individual keys.

The thing I'm trying to puzzle out is what set of conditions causes this log message. Let me see if I can find the corresponding nginx log to get more info here

**Comment by jbuck** [comment]
Here's the corresponding nginx request:

```js
{
  "insertId": "1vzqeyyfoqj73z",
  "jsonPayload": {
    "agent": "python-requests/2.7.0 CPython/2.7.13 Linux/3.2.40",
    "bytes_sent": "58",
    "code": "400",
    "gzip_ratio": "-",
    "referrer": "-",
    "remote_ip": "127.0.0.1",
    "req_time": "0.001",
    "request": "POST /v2 HTTP/1.1",
    "res_time": "0.001"
  },
  "labels": {
    "application": "fxa",
    "compute.googleapis.com/resource_name": "fxa-prod-default-fxa_verifier",
    "env": "prod",
    "stack": "default",
    "type": "fxa_verifier"
  },
  "logName": "projects/moz-fx-fxa-prod-0712/logs/nginx_access",
  "receiveTimestamp": "2019-01-30T09:40:14.953986696Z",
  "resource": {
    "labels": {
      "instance_id": "i-076ea1b1ea3af7769",
      "project_id": "moz-fx-fxa-prod-0712",
      "zone": "us-west-2b"
    },
    "type": "gce_instance"
  },
  "timestamp": "2019-01-30T09:40:11Z"
}
```

Knowing that this is a POST /v2 I was able to replicate this locally pretty easily via `curl -H 'Content-type: application/json' -X POST http://127.0.0.1:60447/v2` which will log `{"op":"bid.summary","name":"bid.summary","time":1548879345023,"pid":94805,"v":1,"hostname":"jbuckley-23775","agent":"curl/7.54.0","remoteAddressChain":["127.0.0.1"],"api":2,"err":{"reason":"missing assertion parameter","code":400},"code":400}` which has the wrong `err` type present.

I think this is because `err` gets added to the summary here: https://github.com/mozilla/browserid-verifier/blob/6f941095ac0f679d2101f8828087fd99095b7b77/lib/v2.js#L109 which then gets logged.
