### ISSUE TITLE
Remove footguns for verifying FxA generated assertions

### ISSUE THREAD

**Issue by ckarlof** [mozilla/browserid-verifier#25]
IMO, there are too many footguns to trap FxA-only reliers (i.e., reliers who *only* want to accept FxA assertions) when verifying and extracting information from FxA generated assertions. The [Mozilla FxA Sync token server](such a service: https://github.com/mozilla-services/tokenserver) is an example of such a service. Here are two pitfalls I can think of:

1) The relier needs to check that the assertion is really backed by an authority it trusts. For example, the token server configures itself with a list of `allowedIssuers` and checks that the issuer of the assertion is on that list: https://github.com/mozilla-services/tokenserver/blob/b55e9533835258f16bf1611521a9efc11aa2afbc/tokenserver/verifiers.py#L90

2) Another issue is that the FxA uid is buried in a non-routable email (i.e., `<uid>@accounts.firefox.com`), which is returned as `email` to the caller. To extract the proper FxA `uid`, the relier needs to parse the returned `email`.

I don't expect these checks to be reliably employed as the number and type of reliers scales.

A simple mitigation would be to provide an FxA-only verifier endpoint, which only verifies FxA assertions, and extracts and returns the user information in a more meaningful format.

**Comment by rfk** [comment]
There will be no more browserid reliers.  OAuth all the things!  Closing this out.
