### ISSUE TITLE
Consider dropping the minimal/default number of agents for load tests

### ISSUE THREAD

**Issue by jbonacci** [mozilla/browserid-verifier#58]
We are finding that with a single instance, 5 agents or even 2 agents per 20 users can cause 503s on the host.

For the most recent release, we found that 20 users and 1 agent prevented 503s.
This seems too late, but we might want to scale this better going forward given the number and size of instances in Stage.

**Comment by rfk** [comment]
This repo is maintenance-only at this point; closing out old feature/enhancement bugs
