### ISSUE TITLE
verifier v2 provides wrong error messages when assertions are malformed

### ISSUE THREAD

**Issue by ncalexan** [mozilla/browserid-verifier#60]
My internal test suite shows different error messages from the v1 verifier and v2 verifier.  I think the v2 verifier is wrong.  I'm using the following endpoints for v1 and v2:
```
  public static String VERIFIER_URL_10 = "https://verifier.login.persona.org/verify";
  public static String VERIFIER_URL_20 = "https://verifier.accounts.firefox.com/v2";
```
A representative failing test is at [1], and looks like:
```
  @Test
  public void testCertificateExpired() throws Exception {
    long ciat = System.currentTimeMillis() - 2;
    long cexp = ciat + 1;
    long aiat = System.currentTimeMillis();
    long aexp = aiat + JSONWebTokenUtils.DEFAULT_ASSERTION_DURATION_IN_MILLISECONDS;
    String certificate = mockMyIdTokenFactory.createMockMyIDCertificate(publicKey, TEST_USERNAME, ciat, cexp);
    String assertion = JSONWebTokenUtils.createAssertion(privateKey, certificate, TEST_AUDIENCE, JSONWebTokenUtils.DEFAULT_ASSERTION_ISSUER, aiat, aexp);
    assertVerifyFailure(TEST_AUDIENCE, assertion, "assertion has expired");
  }
```
You can see that the certificate is issued in the past, is short-lived, and expires immediately; but the assertion is long-lived and includes the time of verification.  I'm getting "certificate expired" instead of "assertion has expired" like I used to.

A minor issue, but it's already really hard to debug these things.  Let's not make them harder!

[1] https://github.com/mozilla-services/android-sync/blob/cdafc277cea4228f8a494498b984f979ec68be5c/src/test/java/org/mozilla/gecko/browserid/test/TestLiveMockMyIDTokenFactory.java#L146

**Comment by rfk** [comment]
This repo is maintenance-only at this point; closing out old feature/enhancement bugs
