### ISSUE TITLE
Use mozlog for logging

### ISSUE THREAD

**Issue by rfk** [mozilla/browserid-verifier#64]
It's the new hotness, we should add it like so: https://github.com/mozilla/fxa-profile-server/pull/74

**Comment by vladikoff** [comment]
It's been 2 years with this bug and seems like no one really asked for this functionality. Please reopen if still needed.

**Comment by jbuck** [comment]
It's not exactly the new hotness, but it's more compatible with Stackdriver Logging, so... I'd like this!
