### ISSUE TITLE
Errors when trying to install on Node 0.12

### ISSUE THREAD

**Issue by pdehaan** [mozilla/browserid-verifier#66]
Looks like a downstream issue w/ **toobusy**... But we should try and make this Node 0.12 (current stable) compatible. Actually, @shane-tomlinson just reported that this isn't working in Node 0.10.32 either.

Ref: https://github.com/lloyd/node-toobusy/issues/45

Screenshot: https://cloudup.com/cOktBSWibQA

**Comment by vladikoff** [comment]
this was fixed https://github.com/mozilla/browserid-verifier/commit/4a30fd03e6aeb2df1b6b13132f9c82440b098beb
