### ISSUE TITLE
Create Release 0.3.1 with Docker stuff

### ISSUE THREAD

**Issue by mostlygeek** [mozilla/browserid-verifier#75]
I want to test that the docker container automatically builds and pushes tags. There are some changes to master since 0.3.0. Is it ok to release a 0.3.1 with the latest changes and the docker stuff?

**Comment by rfk** [comment]
sounds good; do you have the necessary perms, or want me to take care of it?

**Comment by rfk** [comment]
Looks like this was done: https://github.com/mozilla/browserid-verifier/releases/tag/0.3.1
