### ISSUE TITLE
Containerized browserid-verifier uses more CPU than native one

### ISSUE THREAD

**Issue by mostlygeek** [mozilla/browserid-verifier#76]
I deployed a single tokenserver canary into production with the container. It appears that the CPU usage is much higher than the other production servers: 

![high cpu](http://i.imgur.com/3SpcJaC.png)

In stage testing it was the verifier container that was using up the bulk of the CPU. 

I suspect that this may be an issue that node4 requires a different compile flag for [browserid-crypto - usage](https://github.com/mozilla/browserid-crypto#usage)

**Comment by mostlygeek** [comment]
The base docker container has g++ 4.9.2 installed: 
````
root@cb4c043c59c3:/# apt show g++
Package: g++
Status: install ok installed
Priority: optional
Section: devel
Installed-Size: 34.8 kB
Maintainer: Debian GCC Maintainers <debian-gcc@lists.debian.org>
Source: gcc-defaults (1.136)
Version: 4:4.9.2-2
Provides: c++-compiler
Depends: cpp (>= 4:4.9.2-2), gcc (>= 4:4.9.2-2), g++-4.9 (>= 4.6.4-1~), gcc-4.9 (>= 4.6.4-1~)
Suggests: g++-multilib
Download-Size: unknown
APT-Manual-Installed: yes
APT-Sources: /var/lib/dpkg/status
Description: GNU C++ compiler
 This is the GNU C++ compiler, a fairly portable optimizing compiler for C++.
 .
 This is a dependency package providing the default GNU C++ compiler.
````

**Comment by vladikoff** [comment]
> I suspect that this may be an issue that node4 requires a different compile flag for browserid-crypto - usage

Hm also check if the optional dependency `bignum` (or `bigint`) had issues installing.
Be aware that it could be a node 0.10 vs node 4 issues rather than  `Containerized browserid-verifier vs native `

**Comment by mostlygeek** [comment]
@vladikoff do you think we should bump this back down to a node v0.10 base container?

**Comment by mostlygeek** [comment]
Looking more carefully through the [docker build ...](https://circleci.com/gh/mozilla/browserid-verifier/6) for the container it seems that `bigint` failed to build correctly.

**Comment by vladikoff** [comment]
@mostlygeek right, local-verify uses https://github.com/mozilla/browserid-crypto/releases/tag/v0.7.0 currently, not the latest code with my fix here: https://github.com/mozilla/browserid-crypto/commit/15e2e51bc4b52431aa925d53d34eddb8a97d9428

So your container is not using the native library.
