### ISSUE TITLE
Provide a /__version__ endpoint and return the current running version 

### ISSUE THREAD

**Issue by vladikoff** [mozilla/browserid-verifier#93]
Just like https://accounts.firefox.com/ver.json

cc @jbuck @jrgm

**Comment by rfk** [comment]
Is this for use in fxa-dev, or production monitoring, or both?  Depending on your use-case I have a counter-proposal: let's try to avoid publicly exposing the verifier at all, and switch any consumers to doing local verification instead.

Eventually I'd like https://verifier.accounts.firefox.com/ to go away entirely...

**Comment by vladikoff** [comment]
> production monitoring

👍

**Comment by rfk** [comment]
TBH, I wonder whether it's worth the effort to include verifier.accounts.firefox.com in said monitoring, given that none of our services depend on it internally, and it's basically only used by self-hosters at this point.

What could be useful though, is to have fxa-oauth-server report the version of its locally-running verifier instance.  So it's probably worth adding for that even if the public verifier goes away at some point.

**Comment by jbuck** [comment]
I'd like to switch verifier.a.f.o over to Dockerflow so it'll be easier for
@jrgm and I to do deploys - that service hasn't had a deploy in two years.

**Comment by vladikoff** [comment]
:dagger:

**Comment by jbuck** [comment]
> I'd like to switch verifier.a.f.o over to Dockerflow so it'll be easier for @jrgm and I to do deploys - that service hasn't had a deploy in two years.

So I had to do this in a hurry when the service was killed by Meltdown restarts - I can use the `/status` endpoint but I'd like to switch to the standard `/__heartbeat__`, `/__lbheartbeat__`, and `__version__` endpoints
