### ISSUE TITLE
Upgrade to node 6?

### ISSUE THREAD

**Issue by jbuck** [mozilla/browserid-verifier#95]
I was going to rev this, but it's still on node 4. Node 4 support goes away in April 2018. Should we look at upgrading this to node 6, or is it possible that we won't be using this by then?

cc @rfk

**Comment by rfk** [comment]
> is it possible that we won't be using this by then?

I wouldn't count on it; let's definitely look at revving to node 6, and maybe we can be free of this before *that* goes EOL...
